version: '3.8'

services:
  research_gstreamer:
    image: research_gstreamer:0.1.0
    container_name: research_gstreamer
    build: .
    cap_add:
      - NET_ADMIN
    volumes:
      - ./:/app
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mount the X11 Unix socket - Display window in container
      - /mnt/wslg/PulseServer:/mnt/wslg/PulseServer # PulseServer socket - Play audio in container
    environment:
      - DISPLAY=${DISPLAY}  # Pass the host DISPLAY variable - Display window in container
      - PULSE_SERVER=unix:/mnt/wslg/PulseServer # Play audio in container
      - XDG_RUNTIME_DIR=/run/user/1/ # Prevent raise error message XDG_RUNTIME_DIR is invalid
    network_mode: "host"
    tty: True
    mem_limit: 1g
    cpus: 2
